// ============================================================
// DATA
// ============================================================
const LANGS = {
  ru: {
    letters: ['а','б','в','г','д','е','ж','з','и','к','л','м','н','о','п','р','с','т','у','ф','х','ц','ч','ш','э','я'],
    lettersDisplay: ['А','Б','В','Г','Д','Е','Ж','З','И','К','Л','М','Н','О','П','Р','С','Т','У','Ф','Х','Ц','Ч','Ш','Э','Я'],
    syllables: ['ма','па','ка','на','ба','да','та','са','ла','ра','ва','га','жа','за','фа','ха','ча','ша','мо','по','ко','но','бо','до','то','со','ло','ро','во','го','му','пу','ку','ну','бу','ду','ту','су','лу','ру','ву','гу','ми','пи','ки','ни','би','ди','ти','си','ли','ри','ви','ги','ме','пе','ке','не','бе','де','те','се','ле','ре','ве','ге'],
    syllablesDisplay: ['МА','ПА','КА','НА','БА','ДА','ТА','СА','ЛА','РА','ВА','ГА','ЖА','ЗА','ФА','ХА','ЧА','ША','МО','ПО','КО','НО','БО','ДО','ТО','СО','ЛО','РО','ВО','ГО','МУ','ПУ','КУ','НУ','БУ','ДУ','ТУ','СУ','ЛУ','РУ','ВУ','ГУ','МИ','ПИ','КИ','НИ','БИ','ДИ','ТИ','СИ','ЛИ','РИ','ВИ','ГИ','МЕ','ПЕ','КЕ','НЕ','БЕ','ДЕ','ТЕ','СЕ','ЛЕ','РЕ','ВЕ','ГЕ'],
    task: 'Нажми на букву, которую слышишь!',
    taskSyllable: 'Нажми на слог, который слышишь!',
    prompt: 'Слушай внимательно!',
    promptSyllable: 'Слушай слог!',
    correct: ['Отлично!','Супер!','Ура!','Верно!','Молодец!','Браво!'],
    wrong: ['Попробуй ещё раз!','Почти!','Ещё раз, ты сможешь!'],
    next: 'Дальше →',
    result: 'Молодец!',
    restart: 'Играть снова',
    backMenu: 'В меню',
    lang: 'ru-RU',
    stickerMsg: 'Ты заработал наклейку за сегодня!',
    alreadySticker: 'Наклейка уже есть сегодня!',
    repeatBtn: 'Повтори',
    storyPrompt: (name, age, city) =>
      `Напиши волшебную короткую сказку (примерно 200 слов) на русском языке для ребёнка по имени ${name}, ${age} лет${city ? `, из ${city}` : ''}. Главный герой — сам ${name}. В сказке есть говорящий рыжий кот, который помогает учить буквы. Сказка добрая, с хорошим концом. Начни с названия сказки на отдельной строке.`,
    ui: {
      profileTitle: 'Привет! Я БуквоКот!',
      profileSub: 'Расскажи мне о себе',
      labelName: 'Имя ребёнка', labelAge: 'Возраст', labelBirthday: 'День рождения', labelCity: 'Город',
      go: 'Поехали! 🚀',
      menuGames: '🎮 Игры', navHome: 'Главная', navGallery: 'Наклейки', navSettings: 'Настройки',
      gameNames: ['Какая буква?','Какой слог?','Слова','Мемори'],
      gameBestPre: 'Лучший: ',
      dailyLabel: 'Сегодняшний прогресс', dailySub: 'Пройди игру, чтобы заработать звезду!', dailyDone: 'Все звёзды собраны!',
      galleryTitle: 'Мои наклейки',
      prizeTitle: '🎁 Супер-приз!',
      prizeDesc: 'Собери 3 наклейки и получи волшебную сказку про себя!',
      prizeLocked: 'Ещё нужно: ', getStory: 'Получить сказку! ✨',
      storyTitle: 'Моя сказка', loadingText: 'Котик пишет сказку...',
      readAloud: 'Прочитай вслух 🔊', newStory: 'Новая сказка 🔄',
      settingsTitle: 'Настройки', settingsProfile: '👤 Профиль', settingsLang: '🌍 Язык игры',
      sLabelName: 'Имя', sLabelAge: 'Возраст', sLabelBirthday: 'День рождения', sLabelCity: 'Город',
      sLabelApi: 'Groq API-ключ для сказок',
      apiNote: 'Бесплатный ключ: console.groq.com → API Keys',
      save: 'Сохранить', saveKey: 'Сохранить ключ', reset: 'Сбросить прогресс',
      noApiKey: 'Добавь Groq API-ключ в Настройках! (бесплатно)',
      javascriptsubjectReading: 'Чтение',
subjectMath: 'Математика',
subjectLanguages: 'Языки',
levelLabel: 'Уровень',
comingSoon: 'Скоро!',
subjectGameNames: {
  letter:'Какая буква?', syllable:'Какой слог?', word:'Слова',
  count:'Счёт', compare:'Больше/меньше',
  vocab:'Словарь', translate:'Перевод',
  },
    }
  },
  uk: {
    letters: ['а','б','в','г','д','е','є','ж','з','и','і','ї','к','л','м','н','о','п','р','с','т','у','ф','х','ц','ч','ш','я'],
    lettersDisplay: ['А','Б','В','Г','Д','Е','Є','Ж','З','И','І','Ї','К','Л','М','Н','О','П','Р','С','Т','У','Ф','Х','Ц','Ч','Ш','Я'],
    syllables: ['ма','па','ка','на','ба','да','та','са','ла','ра','ва','га','жа','за','фа','ха','ча','ша','мо','по','ко','но','бо','до','то','со','ло','ро','во','го','му','пу','ку','ну','бу','ду','ту','су','лу','ру','ву','гу','ми','пи','ки','ни','би','ди','ти','си','ли','ри','ви','ги','ме','пе','ке','не','бе','де','те','се','ле','ре','ве','ге'],
    syllablesDisplay: ['МА','ПА','КА','НА','БА','ДА','ТА','СА','ЛА','РА','ВА','ГА','ЖА','ЗА','ФА','ХА','ЧА','ША','МО','ПО','КО','НО','БО','ДО','ТО','СО','ЛО','РО','ВО','ГО','МУ','ПУ','КУ','НУ','БУ','ДУ','ТУ','СУ','ЛУ','РУ','ВУ','ГУ','МИ','ПИ','КИ','НИ','БИ','ДИ','ТИ','СИ','ЛИ','РИ','ВИ','ГИ','МЕ','ПЕ','КЕ','НЕ','БЕ','ДЕ','ТЕ','СЕ','ЛЕ','РЕ','ВЕ','ГЕ'],
    task: 'Натисни на літеру, яку чуєш!',
    taskSyllable: 'Натисни на склад, який чуєш!',
    prompt: 'Слухай уважно!',
    promptSyllable: 'Слухай склад!',
    correct: ['Чудово!','Супер!','Ура!','Правильно!','Молодець!','Браво!'],
    wrong: ['Спробуй ще раз!','Майже!','Ще раз, ти зможеш!'],
    next: 'Далі →',
    result: 'Молодець!',
    restart: 'Грати знову',
    backMenu: 'У меню',
    lang: 'uk-UA',
    stickerMsg: 'Ти заробив наліпку за сьогодні!',
    alreadySticker: 'Наліпка вже є сьогодні!',
    repeatBtn: 'Повтори',
    storyPrompt: (name, age, city) =>
      `Напиши чарівну коротку казку (приблизно 200 слів) українською мовою для дитини на ім'я ${name}, ${age} років${city ? `, з ${city}` : ''}. Головний герой — сам ${name}. У казці є говорючий рудий кіт, який допомагає вчити літери. Казка добра, з хорошим кінцем. Почни з назви казки на окремому рядку.`,
    
    ui: {
      profileTitle: 'Привіт! Я БукваКіт!',
      profileSub: 'Розкажи мені про себе',
      labelName: 'Ім\'я дитини', labelAge: 'Вік', labelBirthday: 'День народження', labelCity: 'Місто',
      go: 'Вперед! 🚀',
      menuGames: '🎮 Ігри', navHome: 'Головна', navGallery: 'Наліпки', navSettings: 'Налаштування',
      gameNames: ['Яка літера?','Який склад?','Слова','Меморі'],
      gameBestPre: 'Найкращий: ',
      dailyLabel: 'Прогрес за сьогодні', dailySub: 'Пройди гру, щоб заробити зірку!', dailyDone: 'Усі зірки зібрані!',
      galleryTitle: 'Мої наліпки',
      prizeTitle: '🎁 Супер-приз!',
      prizeDesc: 'Збери 3 наліпки та отримай чарівну казку про себе!',
      prizeLocked: 'Ще потрібно: ', getStory: 'Отримати казку! ✨',
      storyTitle: 'Моя казка', loadingText: 'Котик пише казку...',
      readAloud: 'Прочитай вголос 🔊', newStory: 'Нова казка 🔄',
      settingsTitle: 'Налаштування', settingsProfile: '👤 Профіль', settingsLang: '🌍 Мова гри',
      sLabelName: 'Ім\'я', sLabelAge: 'Вік', sLabelBirthday: 'День народження', sLabelCity: 'Місто',
      sLabelApi: 'Groq API-ключ для казок',
      apiNote: 'Безкоштовний ключ: console.groq.com → API Keys',
      save: 'Зберегти', saveKey: 'Зберегти ключ', reset: 'Скинути прогрес',
      noApiKey: 'Додай Groq API-ключ у Налаштуваннях! (безкоштовно)',
      subjectReading: 'Читання',
subjectMath: 'Математика',
subjectLanguages: 'Мови',
levelLabel: 'Рівень',
comingSoon: 'Незабаром!',
subjectGameNames: {
  letter:'Яка літера?', syllable:'Який склад?', word:'Слова',
  count:'Лічба', compare:'Більше/менше',
  vocab:'Словник', translate:'Переклад'
},
    }
  },
  en: {
    letters: ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'],
    lettersDisplay: ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'],
    syllables: ['ma','pa','ka','na','ba','da','ta','sa','la','ra','va','ga','mo','po','ko','no','bo','do','to','so','lo','ro','vo','go','mu','pu','ku','nu','bu','du','tu','su','lu','ru','vu','gu','me','pe','ke','ne','be','de','te','se','le','re','ve','ge','mi','pi','ki','ni','bi','di','ti','si','li','ri','vi','gi'],
    syllablesDisplay: ['MA','PA','KA','NA','BA','DA','TA','SA','LA','RA','VA','GA','MO','PO','KO','NO','BO','DO','TO','SO','LO','RO','VO','GO','MU','PU','KU','NU','BU','DU','TU','SU','LU','RU','VU','GU','ME','PE','KE','NE','BE','DE','TE','SE','LE','RE','VE','GE','MI','PI','KI','NI','BI','DI','TI','SI','LI','RI','VI','GI'],
    task: 'Tap the letter you hear!',
    taskSyllable: 'Tap the syllable you hear!',
    prompt: 'Listen carefully!',
    promptSyllable: 'Listen to the syllable!',
    correct: ['Great!','Super!','Yay!','Correct!','Amazing!','Bravo!'],
    wrong: ['Try again!','Almost!','One more time!'],
    next: 'Next →',
    result: 'Well done!',
    restart: 'Play again',
    backMenu: 'Menu',
    lang: 'en-US',
    stickerMsg: 'You earned a sticker today!',
    alreadySticker: 'You already have today\'s sticker!',
    repeatBtn: 'Repeat',
    storyPrompt: (name, age, city) =>
      `Write a short magical fairy tale (about 200 words) in English for a child named ${name}, age ${age}${city ? `, from ${city}` : ''}. The main character is ${name} themselves. There is a talking ginger cat who helps learn letters. The story is kind with a happy ending. Start with the story title on a separate line.`,
    ui: {
      profileTitle: 'Hi! I\'m LetterCat!',
      profileSub: 'Tell me about yourself',
      labelName: 'Child\'s name', labelAge: 'Age', labelBirthday: 'Birthday', labelCity: 'City',
      go: 'Let\'s go! 🚀',
      menuGames: '🎮 Games', navHome: 'Home', navGallery: 'Stickers', navSettings: 'Settings',
      gameNames: ['What letter?','What syllable?','Words','Memory'],
      gameBestPre: 'Best: ',
      dailyLabel: 'Today\'s progress', dailySub: 'Play a game to earn a star!', dailyDone: 'All stars collected!',
      galleryTitle: 'My Stickers',
      prizeTitle: '🎁 Super Prize!',
      prizeDesc: 'Collect 3 stickers to get a magical story about you!',
      prizeLocked: 'Still need: ', getStory: 'Get my story! ✨',
      storyTitle: 'My Story', loadingText: 'Kitty is writing your story...',
      readAloud: 'Read aloud 🔊', newStory: 'New story 🔄',
      settingsTitle: 'Settings', settingsProfile: '👤 Profile', settingsLang: '🌍 Game language',
      sLabelName: 'Name', sLabelAge: 'Age', sLabelBirthday: 'Birthday', sLabelCity: 'City',
      sLabelApi: 'Groq API key for stories',
      apiNote: 'Free key at console.groq.com → API Keys',
      save: 'Save', saveKey: 'Save key', reset: 'Reset progress',
      noApiKey: 'Add your free Groq API key in Settings!',
      subjectReading: 'Reading',
subjectMath: 'Math',
subjectLanguages: 'Languages',
levelLabel: 'Level',
comingSoon: 'Coming soon!',
subjectGameNames: {
  letter:'What letter?', syllable:'What syllable?', word:'Words',
  count:'Count', compare:'More/Less',
  vocab:'Vocab', translate:'Translate'
},
    }
  }
};

const STICKER_EMOJIS = ['⭐','🌟','🏆','🎉','🌈','🦋','🌸','🐾','💎','🎀','🍀','🔥','💫','🎵','🌙','🎨','🦄','🍭','🎈','🌺','💖','🎯','🚀','🎠'];

const SUBJECTS = [
  {
    key: 'reading', emoji: '📚', color: '#FF6B35', dark: '#c04a1a',
    games: [
      { type: 'letter',   emoji: '👂', locked: false },
      { type: 'syllable', emoji: '🧩', locked: false },
      { type: 'word',     emoji: '🚂', locked: true  },
    ]
  },
  {
    key: 'math', emoji: '🔢', color: '#4ECDC4', dark: '#0f766e',
    games: [
      { type: 'count',   emoji: '🔢', locked: true },
      { type: 'compare', emoji: '⚖️', locked: true },
    ]
  },
  {
    key: 'languages', emoji: '🌍', color: '#A855F7', dark: '#7e22ce',
    games: [
      { type: 'vocab',     emoji: '🖼️', locked: true },
      { type: 'translate', emoji: '🔤', locked: true },
    ]
  },
];
